### ISSUE TITLE
Error when using a custom `Result` type

### ISSUE THREAD

**Issue by althonos** [lo48576/opaque_typedef#13]
Hi !

When trying to derive `OpaqueTypedefUnsized` within a module using a custom `Result` type (which is quite frequent for a library exposing its own error type: 
```rust
type Result = std::result::Result<T, Error>
```

the derive will fail because the generated functions expect the local `Result` to be `std::result::Result`.

**Comment by lo48576** [comment]
Ok, confirmed.
Thank you for reporting.

**Comment by lo48576** [comment]
I'll release a new version (0.0.5) soon.

**Comment by lo48576** [comment]
Released.
